#!/bin/bash

# Ensure the script is run as root
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

# Source necessary configurations
source ./system_config.sh

# Run system backup
./system_backup.sh

# Determine root device and conditional backup logic (currently disabled)
# root_dev=$(grep -oPr "root=[^\s]*" /boot/cmdline.txt | awk -F= '{print $NF}')
# if [[ "$root_dev" == "/dev/mmcblk0p7" ]]; then
#     cp -rf ./boot/config-noobs-normal.txt /boot/config.txt.bak
# else
#     cp -rf ./boot/config-normal.txt /boot/config.txt.bak
# fi

# Backup the current configuration
cp -rf /boot/config.txt /boot/config.txt.bak

# Append new settings to the backup configuration file
{
  echo "hdmi_force_hotplug=1"
  echo "hdmi_force_edid_audio=1"
  echo "dtparam=i2c_arm=on"
  echo "dtparam=spi=on"
  echo "enable_uart=1"
  echo "display_rotate=0"
  echo "max_usb_current=1"
  echo "config_hdmi_boost=7"
  echo "hdmi_group=2"
  echo "hdmi_mode=1"
  echo "hdmi_mode=87"
  echo "hdmi_drive=2"
  echo "hdmi_cvt 800 480 60 6 0 0 0"
} >> /boot/config.txt.bak

# Ensure directory exists
mkdir -p /etc/X11/xorg.conf.d

# Conditional configurations based on Debian version
if [[ "$deb_version" < "12.1" ]]; then
  cp -rf ./usr/99-fbturbo.conf-HDMI /usr/share/X11/xorg.conf.d/
fi

cp ./usr/40-libinput.conf-0 /etc/X11/xorg.conf.d/
cp ./usr/inittab /etc/

# Mark installation
echo "hdmi:capacity:MPI5001:0:800:480" > ./.have_installed

# Sync file system
sync

# Conditional script execution based on arguments
if [[ $# -eq 1 ]]; then
  ./rotate.sh "$1"
elif [[ $# -gt 1 ]]; then
  echo "Too many parameters"
  exit 2
fi

# Reboot system
echo "Rebooting now..."
reboot
